/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.Persona;
import javax.swing.DefaultComboBoxModel;
import Funciones.Validar;
import static Interfaces.CargarArchivo.arbolApp;
import javax.swing.JOptionPane;

/**
 *
 * @author salom
 */
public class BusquedaTitulos extends javax.swing.JFrame {
    
    DefaultComboBoxModel modeloResultado = new DefaultComboBoxModel();
    private Validar validar = new Validar();
    private Persona[] resultado;
    
    /**
     * Creates new form BusquedaTitulos
     */
    public BusquedaTitulos() {
        initComponents();
    }
    
    private void llenarComboBox(Persona[] arreglo) {
        for (int i = 0; i < arreglo.length; i++) {
            int numeroAsociado = i + 1;
            String nombreResultado = numeroAsociado + ". " + arreglo[i].getNombreUnico() + ", " + arreglo[i].getTituloMobiliario();
            modeloResultado.addElement(nombreResultado);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloVentana = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        buscarBtn = new javax.swing.JLabel();
        resultadosPersona = new javax.swing.JComboBox<>();
        info = new javax.swing.JPanel();
        verInfoBtn = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        menu = new javax.swing.JPanel();
        menuBtn = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloVentana.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        tituloVentana.setForeground(new java.awt.Color(0, 51, 0));
        tituloVentana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloVentana.setText("BÚSQUEDA POR TITULO");
        getContentPane().add(tituloVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 310, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Por favor, ingrese el titulo del familiar que desea buscar:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 310, 30));

        jPanel1.setBackground(new java.awt.Color(0, 51, 0));
        jPanel1.setForeground(new java.awt.Color(0, 51, 0));

        buscarBtn.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        buscarBtn.setForeground(new java.awt.Color(255, 255, 255));
        buscarBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buscarBtn.setText("BUSCAR");
        buscarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, 50));

        resultadosPersona.setBackground(new java.awt.Color(255, 255, 255));
        resultadosPersona.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        resultadosPersona.setModel(modeloResultado);
        resultadosPersona.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(resultadosPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 430, 40));

        info.setBackground(new java.awt.Color(0, 51, 0));

        verInfoBtn.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        verInfoBtn.setForeground(new java.awt.Color(255, 255, 255));
        verInfoBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verInfoBtn.setText("VER INFORMACIÓN");
        verInfoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verInfoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verInfoBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout infoLayout = new javax.swing.GroupLayout(info);
        info.setLayout(infoLayout);
        infoLayout.setHorizontalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(verInfoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        infoLayout.setVerticalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(verInfoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 220, 50));

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 300, 50));

        menu.setBackground(new java.awt.Color(0, 51, 0));
        menu.setForeground(new java.awt.Color(0, 51, 0));
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuBtn.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        menuBtn.setForeground(new java.awt.Color(255, 255, 255));
        menuBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn.setText("MENÚ");
        menuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 190, 50));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarBtnMouseClicked
        String tituloBuscar = titulo.getText();

        if (arbolApp.buscarTitulo(tituloBuscar) != null) {
            resultado = arbolApp.buscarTitulo(tituloBuscar);
            this.llenarComboBox(arbolApp.buscarTitulo(tituloBuscar));
        } else {
            resultado = null;
            JOptionPane.showMessageDialog(null, "No se encontraron resultados de la busqueda.");
        }
    }//GEN-LAST:event_buscarBtnMouseClicked

    private void verInfoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verInfoBtnMouseClicked
        if (resultado != null) {
            String seleccion = (String) resultadosPersona.getSelectedItem();
            String[] separarSeleccion = seleccion.split(". ");

            int numero = validar.validarNumeros(separarSeleccion[0])-1;

            if (numero != -1) { // Verifica que el número sea válido
                if (validar.validarIndice(resultado.length - 1, 0, numero)) {
                    
                    JOptionPane.showMessageDialog(null, resultado[numero].toString());
                } else {
                    JOptionPane.showMessageDialog(null, "El número está fuera del índice.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Debe seleccionar un número válido.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay resultados para ver detalles.");
        }
    }//GEN-LAST:event_verInfoBtnMouseClicked

    private void menuBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtnMouseClicked
        Menu menu = new Menu();
        menu.setLocationRelativeTo(null);
        menu.setResizable(false);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusquedaTitulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusquedaTitulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusquedaTitulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusquedaTitulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusquedaTitulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buscarBtn;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel menuBtn;
    private javax.swing.JComboBox<String> resultadosPersona;
    private javax.swing.JTextField titulo;
    private javax.swing.JLabel tituloVentana;
    private javax.swing.JLabel verInfoBtn;
    // End of variables declaration//GEN-END:variables
}
