/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author salom
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        salirPnl = new javax.swing.JPanel();
        salirBtn = new javax.swing.JLabel();
        cargarArchivoPnl = new javax.swing.JPanel();
        cargarArchivoBtn = new javax.swing.JLabel();
        buscarPnl = new javax.swing.JPanel();
        buscarBtn = new javax.swing.JLabel();
        buscarAntepasdosPnl = new javax.swing.JPanel();
        buscarAntepasadosBtn = new javax.swing.JLabel();
        mostrarArbolPnl = new javax.swing.JPanel();
        mostrarArbolBtn = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salirPnl.setBackground(new java.awt.Color(0, 51, 0));

        salirBtn.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        salirBtn.setForeground(new java.awt.Color(255, 255, 255));
        salirBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salirBtn.setText("SALIR");
        salirBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout salirPnlLayout = new javax.swing.GroupLayout(salirPnl);
        salirPnl.setLayout(salirPnlLayout);
        salirPnlLayout.setHorizontalGroup(
            salirPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        salirPnlLayout.setVerticalGroup(
            salirPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salirBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(salirPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 340, 60));

        cargarArchivoPnl.setBackground(new java.awt.Color(0, 51, 0));

        cargarArchivoBtn.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        cargarArchivoBtn.setForeground(new java.awt.Color(255, 255, 255));
        cargarArchivoBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cargarArchivoBtn.setText("CARGAR ARCHIVO");
        cargarArchivoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cargarArchivoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargarArchivoBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cargarArchivoPnlLayout = new javax.swing.GroupLayout(cargarArchivoPnl);
        cargarArchivoPnl.setLayout(cargarArchivoPnlLayout);
        cargarArchivoPnlLayout.setHorizontalGroup(
            cargarArchivoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cargarArchivoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        cargarArchivoPnlLayout.setVerticalGroup(
            cargarArchivoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cargarArchivoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(cargarArchivoPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 340, 60));

        buscarPnl.setBackground(new java.awt.Color(0, 51, 0));

        buscarBtn.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        buscarBtn.setForeground(new java.awt.Color(255, 255, 255));
        buscarBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buscarBtn.setText("BUSCAR");
        buscarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout buscarPnlLayout = new javax.swing.GroupLayout(buscarPnl);
        buscarPnl.setLayout(buscarPnlLayout);
        buscarPnlLayout.setHorizontalGroup(
            buscarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        buscarPnlLayout.setVerticalGroup(
            buscarPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(buscarPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 340, 60));

        buscarAntepasdosPnl.setBackground(new java.awt.Color(0, 51, 0));

        buscarAntepasadosBtn.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        buscarAntepasadosBtn.setForeground(new java.awt.Color(255, 255, 255));
        buscarAntepasadosBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buscarAntepasadosBtn.setText("BUSCAR ANTEPASADOS");
        buscarAntepasadosBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarAntepasadosBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarAntepasadosBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout buscarAntepasdosPnlLayout = new javax.swing.GroupLayout(buscarAntepasdosPnl);
        buscarAntepasdosPnl.setLayout(buscarAntepasdosPnlLayout);
        buscarAntepasdosPnlLayout.setHorizontalGroup(
            buscarAntepasdosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarAntepasadosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        buscarAntepasdosPnlLayout.setVerticalGroup(
            buscarAntepasdosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarAntepasadosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(buscarAntepasdosPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 340, 60));

        mostrarArbolPnl.setBackground(new java.awt.Color(0, 51, 0));
        mostrarArbolPnl.setForeground(new java.awt.Color(0, 51, 0));

        mostrarArbolBtn.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        mostrarArbolBtn.setForeground(new java.awt.Color(255, 255, 255));
        mostrarArbolBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrarArbolBtn.setText("MOSTRAR ÁRBOL");
        mostrarArbolBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostrarArbolBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarArbolBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mostrarArbolPnlLayout = new javax.swing.GroupLayout(mostrarArbolPnl);
        mostrarArbolPnl.setLayout(mostrarArbolPnlLayout);
        mostrarArbolPnlLayout.setHorizontalGroup(
            mostrarArbolPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mostrarArbolBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        mostrarArbolPnlLayout.setVerticalGroup(
            mostrarArbolPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mostrarArbolBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(mostrarArbolPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 340, 60));

        jLabel7.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MENÚ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 60, 270, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarArchivoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarArchivoBtnMouseClicked
        CargarArchivo ca = new CargarArchivo();
        ca.setResizable(false);
        ca.setLocationRelativeTo(null);
        ca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cargarArchivoBtnMouseClicked

    private void buscarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarBtnMouseClicked

    private void buscarAntepasadosBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarAntepasadosBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarAntepasadosBtnMouseClicked

    private void mostrarArbolBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarArbolBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarArbolBtnMouseClicked

    private void salirBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirBtnMouseClicked
        this.dispose();
        JOptionPane.showMessageDialog(null, "¡Gracias, vuelva pronto!");
    }//GEN-LAST:event_salirBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buscarAntepasadosBtn;
    private javax.swing.JPanel buscarAntepasdosPnl;
    private javax.swing.JLabel buscarBtn;
    private javax.swing.JPanel buscarPnl;
    private javax.swing.JLabel cargarArchivoBtn;
    private javax.swing.JPanel cargarArchivoPnl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mostrarArbolBtn;
    private javax.swing.JPanel mostrarArbolPnl;
    private javax.swing.JLabel salirBtn;
    private javax.swing.JPanel salirPnl;
    // End of variables declaration//GEN-END:variables
}
