/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.Persona;
import EDD.Arbol;
import EDD.ListaSimple;
import EDD.NodoArbol;
import Funciones.MostrarArbol;
import Funciones.MostrarLinaje;
import Funciones.Validar;
import static Interfaces.CargarArchivo.arbolApp;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author salom
 */
public class VerAntepasados extends javax.swing.JFrame {
    
    DefaultComboBoxModel modeloResultado = new DefaultComboBoxModel();
    private Validar validar = new Validar();
    private Persona[] resultado;
    /**
     * Creates new form VerAntepasados
     */
    public VerAntepasados() {
        initComponents();
    }
    
    private void llenarComboBox(Persona[] arreglo) {
        for (int i = 0; i < arreglo.length; i++) {
            int numeroAsociado = i + 1;
            String nombreResultado = numeroAsociado + ". " + arreglo[i].getNombreUnico();
            modeloResultado.addElement(nombreResultado);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        buscarBtn = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        resultadosPersona = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        verInfoBtn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        menu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VER ANTEPASADOS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 60, 270, 30));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ingrese el nombre del familiar que desea buscar:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 340, 30));

        jPanel1.setBackground(new java.awt.Color(0, 51, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscarBtn.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        buscarBtn.setForeground(new java.awt.Color(255, 255, 255));
        buscarBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buscarBtn.setText("BUSCAR");
        buscarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarBtnMouseClicked(evt);
            }
        });
        jPanel1.add(buscarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 110, 50));

        inputNombre.setBackground(new java.awt.Color(255, 255, 255));
        inputNombre.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 300, 50));

        resultadosPersona.setBackground(new java.awt.Color(255, 255, 255));
        resultadosPersona.setModel(modeloResultado);
        getContentPane().add(resultadosPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 450, 50));

        jPanel2.setBackground(new java.awt.Color(0, 51, 0));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        verInfoBtn.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        verInfoBtn.setForeground(new java.awt.Color(255, 255, 255));
        verInfoBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verInfoBtn.setText("VER INFORMACIÓN");
        verInfoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verInfoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verInfoBtnMouseClicked(evt);
            }
        });
        jPanel2.add(verInfoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 210, 50));

        jPanel3.setBackground(new java.awt.Color(0, 51, 0));
        jPanel3.setForeground(new java.awt.Color(0, 51, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        menu.setForeground(new java.awt.Color(255, 255, 255));
        menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu.setText("MENÚ");
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });
        jPanel3.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 270, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarBtnMouseClicked
        if (!inputNombre.getText().isEmpty()) {
            String nombreBuscado = inputNombre.getText();
            if (arbolApp.buscarNombreAntepasado(nombreBuscado) != null) {
                resultado = arbolApp.buscarNombreAntepasado(nombreBuscado);
                this.llenarComboBox(arbolApp.buscarNombreAntepasado(nombreBuscado));
            } else {
                resultado = null;
                JOptionPane.showMessageDialog(null, "No se encontraron resultados de la busqueda.");
            }
            inputNombre.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Debe de ingresar un nombre.");
        }
    }//GEN-LAST:event_buscarBtnMouseClicked

    private void verInfoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verInfoBtnMouseClicked
        if (resultado != null) {
            String seleccion = (String) resultadosPersona.getSelectedItem();
            //System.out.println(seleccion);
            String[] separarSeleccion = seleccion.split(". ");
            //System.out.println(Arrays.toString(separarSeleccion));
            int numero = validar.validarNumeros(separarSeleccion[0]) - 1;
            NodoArbol nodo = arbolApp.getArbolL().buscarNombre(resultado[numero].getNombreUnico());
            ListaSimple listaAntepasados =  arbolApp.getArbolL().buscarAncestros(nodo);
            
            System.setProperty("org.graphstream.ui", "swing");
            MostrarLinaje mostarArbol = new MostrarLinaje(listaAntepasados);
            mostarArbol.setVisible(true);
            this.dispose();
            

        } else {
            JOptionPane.showMessageDialog(null, "No hay resultados para ver detalles.");
        }
        
    }//GEN-LAST:event_verInfoBtnMouseClicked

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        Menu m = new Menu();
        m.setVisible(true);
        m.setResizable(false);
        m.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_menuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerAntepasados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerAntepasados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerAntepasados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerAntepasados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerAntepasados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buscarBtn;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel menu;
    private javax.swing.JComboBox<String> resultadosPersona;
    private javax.swing.JLabel verInfoBtn;
    // End of variables declaration//GEN-END:variables
}
